######################################################################
# Automatically generated by qmake (3.1) Mon Nov 8 23:48:36 2021
######################################################################

TEMPLATE = app

QT -= webkit
QT += widgets

SOURCES += qmain.cc dialog.cc
HEADERS += dialog.hh
